language: C
sudo: required

before_install:
before_script:
script:
  - make install_prerequisites
  - make download_additionals
  - make

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: doc/html/
  repo: roboag/doc_robolib
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

notifications:
  email:
    - secure: sAw1dBxsvI/6vd3q/Bo/xBe+RAQoLCPerdS2cVO8yKtK4lhrVaCst2j1xbr9Xr8t0Yyi07lYW7SQ8f5tgPVQ3EDT+0TrzwErvz4tXe7Iv81ucWzca4JaEPu0XipjAGI6u9zJTT3WRG/3488gatO2f4h/1v05kiFVMy9PPkzI9rEW46zxzJy3dZjwkNlc3i0PqT5L9kwuOzcKuE9nVFBNdiG6qttrQYTmeo9yVqOJnEMQou5yd9eu3vUR+FKrDfkKEKnDopVvELKeKpXYpUoEohDcW0Sex5qzhT1nKvypmb01LkjtiqD9C66duXH9d057fqA4UxefTfNWK9rocmDUAs95p5pAdTLzQZerUt9+PX5essCPiU3cc9WNP6N4b0lG7o7tqkiI3jHS7CzelcL4y77NLWPXjE8bJuLAwUVlMm5hSnHnlFQ140wIJSpuJ2BByqE9MRdbveHAORMOPqkxPRMqR0WZCcUJD2GSSBcs5Hex7VO0n7HwFerpe+arePurqUObmQtplJOP3QrD2AZncthJZoAoHPozZQyb/QPzbQcZ4/WXvEv6fEhvZR9h5Ip5HytrJahxBFqGqEr6obUP+fQW4Y3j2d5qlSCcTp0rqQeyUEPAj+eKGoRiaDX1jDjlxBxiHEPxPf5tuLrlIGtb8+823s1DggDgzIPDh2WzNwA=
